###
POST http://localhost:4567/api/auth/register
Content-Type: application/json

{
    "name" : "Chris Farrugia",
    "email": "chris12aug@gmail.com",
    "password1": "test123",
    "password2": "test123"
}



### Login User
POST http://localhost:4567/api/auth/login
Content-Type: application/json

{
    "email": "chris12aug@gmail.com",
    "password": "test123"
}